--- #YAML:1.0
name:               Thread-Conveyor
version:            0.19
abstract:           transport of any data-structure
author:
    - Elizabeth Mattijsen (liz@dijkmat.nl)
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    load:               0
    Thread::Serialize:  0
    Thread::Tie:        0.09
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
